import sys
from PyQt5 import QtWidgets, QtPrintSupport, QtGui, QtCore
from PyQt5.QtCore import Qt 

class Shortcuts(QtWidgets.QDialog):

    def __init__(self, parent):
        QtWidgets.QWidget.__init__(self, parent)
        self.parent = parent 
        
        self.setup_ui()

    def setup_ui(self):
        self.setObjectName("Shortcuts")
        self.resize(306, 307)
        self.layoutWidget = QtWidgets.QWidget(self)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 30, 261, 19))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_15 = QtWidgets.QLabel(self.layoutWidget)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_8.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_8.addWidget(self.label_16)
        self.layoutWidget_2 = QtWidgets.QWidget(self)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 50, 261, 19))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_17 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_9.addWidget(self.label_17)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_9.addWidget(self.label_18)
        self.layoutWidget_27 = QtWidgets.QWidget(self)
        self.layoutWidget_27.setGeometry(QtCore.QRect(20, 70, 261, 19))
        self.layoutWidget_27.setObjectName("layoutWidget_27")
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout(self.layoutWidget_27)
        self.horizontalLayout_43.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.label_85 = QtWidgets.QLabel(self.layoutWidget_27)
        self.label_85.setObjectName("label_85")
        self.horizontalLayout_43.addWidget(self.label_85)
        self.label_86 = QtWidgets.QLabel(self.layoutWidget_27)
        self.label_86.setObjectName("label_86")
        self.horizontalLayout_43.addWidget(self.label_86)
        self.layoutWidget_3 = QtWidgets.QWidget(self)
        self.layoutWidget_3.setGeometry(QtCore.QRect(20, 90, 261, 19))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_19 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_10.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_10.addWidget(self.label_20)
        self.layoutWidget_4 = QtWidgets.QWidget(self)
        self.layoutWidget_4.setGeometry(QtCore.QRect(20, 110, 261, 19))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_21 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_11.addWidget(self.label_21)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_11.addWidget(self.label_22)
        self.layoutWidget_5 = QtWidgets.QWidget(self)
        self.layoutWidget_5.setGeometry(QtCore.QRect(20, 130, 261, 19))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_23 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_12.addWidget(self.label_23)
        self.label_24 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_12.addWidget(self.label_24)
        self.layoutWidget_6 = QtWidgets.QWidget(self)
        self.layoutWidget_6.setGeometry(QtCore.QRect(20, 150, 261, 19))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.layoutWidget_6)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_25 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_13.addWidget(self.label_25)
        self.label_26 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_13.addWidget(self.label_26)
        self.layoutWidget_7 = QtWidgets.QWidget(self)
        self.layoutWidget_7.setGeometry(QtCore.QRect(20, 170, 261, 19))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.layoutWidget_7)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_27 = QtWidgets.QLabel(self.layoutWidget_7)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_14.addWidget(self.label_27)
        self.label_28 = QtWidgets.QLabel(self.layoutWidget_7)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_14.addWidget(self.label_28)
        self.layoutWidget_8 = QtWidgets.QWidget(self)
        self.layoutWidget_8.setGeometry(QtCore.QRect(20, 190, 261, 19))
        self.layoutWidget_8.setObjectName("layoutWidget_8")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.layoutWidget_8)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_29 = QtWidgets.QLabel(self.layoutWidget_8)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_15.addWidget(self.label_29)
        self.label_30 = QtWidgets.QLabel(self.layoutWidget_8)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_15.addWidget(self.label_30)
        self.layoutWidget_9 = QtWidgets.QWidget(self)
        self.layoutWidget_9.setGeometry(QtCore.QRect(20, 210, 261, 19))
        self.layoutWidget_9.setObjectName("layoutWidget_9")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.layoutWidget_9)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_31 = QtWidgets.QLabel(self.layoutWidget_9)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_16.addWidget(self.label_31)
        self.label_32 = QtWidgets.QLabel(self.layoutWidget_9)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_16.addWidget(self.label_32)
        self.layoutWidget_10 = QtWidgets.QWidget(self)
        self.layoutWidget_10.setGeometry(QtCore.QRect(20, 230, 261, 19))
        self.layoutWidget_10.setObjectName("layoutWidget_10")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.layoutWidget_10)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_33 = QtWidgets.QLabel(self.layoutWidget_10)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_17.addWidget(self.label_33)
        self.label_34 = QtWidgets.QLabel(self.layoutWidget_10)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_17.addWidget(self.label_34)
        self.layoutWidget_11 = QtWidgets.QWidget(self)
        self.layoutWidget_11.setGeometry(QtCore.QRect(20, 250, 261, 19))
        self.layoutWidget_11.setObjectName("layoutWidget_11")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.layoutWidget_11)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_35 = QtWidgets.QLabel(self.layoutWidget_11)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_18.addWidget(self.label_35)
        self.label_36 = QtWidgets.QLabel(self.layoutWidget_11)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_18.addWidget(self.label_36)
        self.layoutWidget_12 = QtWidgets.QWidget(self)
        self.layoutWidget_12.setGeometry(QtCore.QRect(20, 270, 261, 19))
        self.layoutWidget_12.setObjectName("layoutWidget_12")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.layoutWidget_12)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_37 = QtWidgets.QLabel(self.layoutWidget_12)
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_19.addWidget(self.label_37)
        self.label_38 = QtWidgets.QLabel(self.layoutWidget_12)
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_19.addWidget(self.label_38)
        self.widget = QtWidgets.QWidget(self)
        self.widget.setGeometry(QtCore.QRect(20, 10, 261, 19))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.layoutWidget.raise_()
        self.layoutWidget_2.raise_()
        self.layoutWidget_27.raise_()
        self.layoutWidget_3.raise_()
        self.layoutWidget_4.raise_()
        self.layoutWidget_5.raise_()
        self.layoutWidget_6.raise_()
        self.layoutWidget_7.raise_()
        self.layoutWidget_8.raise_()
        self.layoutWidget_9.raise_()
        self.layoutWidget_10.raise_()
        self.layoutWidget_11.raise_()
        self.layoutWidget_12.raise_()

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Shortcuts"))
        self.label_15.setText(_translate("Dialog", "Save "))
        self.label_16.setText(_translate("Dialog", "Ctrl + S"))
        self.label_17.setText(_translate("Dialog", "Copy"))
        self.label_18.setText(_translate("Dialog", "Ctrl + C"))
        self.label_85.setText(_translate("Dialog", "Paste"))
        self.label_86.setText(_translate("Dialog", "Ctrl + V"))
        self.label_19.setText(_translate("Dialog", "Cut"))
        self.label_20.setText(_translate("Dialog", "Ctrl + X"))
        self.label_21.setText(_translate("Dialog", "Insert Table"))
        self.label_22.setText(_translate("Dialog", "Ctrl + T"))
        self.label_23.setText(_translate("Dialog", "Bullet List"))
        self.label_24.setText(_translate("Dialog", "Ctrl + Shift + B"))
        self.label_25.setText(_translate("Dialog", "Number List"))
        self.label_26.setText(_translate("Dialog", "Ctrl + Shift + N"))
        self.label_27.setText(_translate("Dialog", "Stats"))
        self.label_28.setText(_translate("Dialog", "Ctrl + L"))
        self.label_29.setText(_translate("Dialog", "Dictionary"))
        self.label_30.setText(_translate("Dialog", "Ctrl + Shift + D"))
        self.label_31.setText(_translate("Dialog", "Find"))
        self.label_32.setText(_translate("Dialog", "Ctrl + F"))
        self.label_33.setText(_translate("Dialog", "Spell check"))
        self.label_34.setText(_translate("Dialog", "Ctrl + Shift + S"))
        self.label_35.setText(_translate("Dialog", "Thesaurus"))
        self.label_36.setText(_translate("Dialog", "Ctrl + Shift + T"))
        self.label_37.setText(_translate("Dialog", "Spell suggestions"))
        self.label_38.setText(_translate("Dialog", "Ctrl + Shift + C"))


